### ISSUE TITLE
Add support for Split View mode

### ISSUE THREAD

**Issue by AlexDerbenew** [elementary/gala#1028]
## Problem
Sometimes it's useful to have application pairs (e.g. Slack+Asana, Telegram+Trello, etc.) in fullscreen mode, but there is no such functionality in Elementary OS. I think a lot of users would like this feature in future releases.

## Proposal
It would be nice if we will be able to open applications in split view like it is possible on macOS (https://support.apple.com/en-us/HT204948).

**Comment by cassidyjames** [comment]
We have half-tiling which is similar to that feature in macOS; I don't think we need to try to also implement split view on top of fullscreen.

**Comment by AlexDerbenew** [comment]
@cassidyjames why do you think this issue should be fully closed?
I agree that it is just a feature for wishlist, but i do not think it should be rejected without even a small research from volunteers

**Comment by cassidyjames** [comment]
@AlexDerbenew issues can be re-opened or converted to discussions, but if there's nothing actionable, then it doesn't make sense to leave it open as an issue.

The reason I closed it in favor of tiling, though, is because the two concepts are in conflict; macOS has Split View and does not have tiling. elementary OS has tiling and does not have split view. Shipping both would be confusing and overlapping, and we don't plan to get rid of tiling—in fact, there is a large amount of user interest in expanding tiling further than its current state.

Another issue is simply to do with how fullscreen works at a more fundamental level in elementary OS (and Mutter, the windowing library on which Gala is built): as far as I know, we can't draw two apps on screen in their "fullscreen" states, but tiled, as macOS does for split view. Instead, I would like to see improvements made to tiling to address any workflow issues.

So: what about Split View is it that you like, and how does that differ from half-tiling in elementary OS today? Let's start there and then we can file actionable improvements instead of asking for _almost_ the same feature as tiling, but called something different. :)
