### ISSUE TITLE
New Firefox window gets moved away from current desktop

### ISSUE THREAD

**Issue by maxlStone** [elementary/gala#1105]
When I open Firefox it gets moved away from the current desktop. If I open a second window of Firefox it stays on the current desktop. Sometimes it gets moved to the desktop left of the currently used one and sometimes to the one on the right.

I get this strange behaviour just with Firefox.
I recognized this problem about 4 weeks ago.

**Comment by cassidyjames** [comment]
This is Firefox trying to be clever and remembering the workspace it was last used on, even when there are dynamic workspaces. There is nothing we can do to change this behavior, it would need to be raised as an issue in Firefox.

**Comment by Blast-City** [comment]
Hi.

Could you give some more info on the elementary and Firefox versions?

I'm not getting this issue on Firefox 87 (Ubuntu repo) and elementary OS 5.1.7 Hera.

**Comment by cassidyjames** [comment]
I think this issue is reproducible when you open Firefox, move it to a secondary workspace, close it, and then re-open it while on the first workspace—or something like that. All I know is occasionally I do see Firefox open itself on a workspace other than the one I'm on, and I believe that's intentional on the Firefox side. 

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1628742

It appears Firefox has explicitly disabled this feature on GNOME due to dynamic workspaces, but it is still enabled in other desktop environments with dynamic workspaces like Pantheon.

**Comment by cassidyjames** [comment]
Ah, you can disable this behavior by setting `widget.disable-workspace-management` in `about:config` to `false`. Then close and re-open Firefox a couple of times to clear out the previously-saved workspace preference, and it should always open on the active workspace.

**Comment by Blast-City** [comment]
On a new profile the setting is set to false by default which should mean that it's working, but I can't replicate the issue. Strange.

Hopefully Firefox revert this change because, in my opinion, it should be up to the OS to decide this kind of behavior.

**Comment by maxlStone** [comment]
I have enabled the "restore previous session" option.

I was able to disable the behaviour with setting `widget.disable-workspace-management` to `true`.
Thanks for the help.
