### ISSUE TITLE
ALT+TAB should cycle open apps, not windows

### ISSUE THREAD

**Issue by nkkollaw** [elementary/gala#125]
This *MIGHT* be debatable, but I personally can't find a case where I want to use ALT+TAB to cycle other windows within the same app, rather than other open apps.

With the current behavior, I have to windows open in A (so A1 and A2), want to switch to B and then back to A1. I usually switch to A2 by mistake, but more frustratingly many many times I correctly switch to B and somehow switch back to A2 instead of A1.

**Comment by Nine-H** [comment]
personally I do a split between google docs and a browser window and alt tab between them almost daily.

**Comment by nkkollaw** [comment]
Sure, everyone has his own workflow. I have multiple VS Code windows open and go back to the browser, so it takes me forever.

I guess the question is what makes more sense.

I know that macOS switches appa, does anyone know what Windowa does, if apps or open windows?

**Comment by olo2552** [comment]
@nkkollaw Windows has the same approach that cycles currently opened windows, instead of unique apps. 
But I think, that the debated feature is unfortunately zero-sum-game. If you decide to use 'switch by apps' approach you are sacrificing key part of ALT-TAB's functionality. The problem is the scenario where I've got one firefox window for youtube and second for development - how could I simply switch between firefoxes then?
+ if your workspace is growing to heavy it should be spllited for many smaller ones - then you still can change your view quickly, but without sacrificing anything <but your resources>.

**Comment by nkkollaw** [comment]
> @nkkollaw Windows has the same approach that cycles currently opened windows, instead of unique apps.

I see. Sorry, I haven't been using Windows since Vista, and I just don't remember :-)

> Plus if your workspace is growing to heavy it should be spllited for many smaller ones - then you still can change your view quickly, but without sacrificing anything .

Yes, I don't use workspaces that much. I know it's SUPER + alt (or arrow?) to switch, though.

I wonder, would it be possibile to add a shortcut like ALT + SHIFT + TAB to cycle apps instead of windows?

**Comment by olo2552** [comment]
> I wonder, would it be possibile to add a shortcut like ALT + SHIFT + TAB to cycle apps instead of windows?
ALT + SHIFT + TAB does <I hope predictably> inversion of ALT + TAB so cycles one window back, instead of one ahead. It cannot be (by maintainers of the system) changed, because is making ALT + TAB complimentary.

**Comment by nkkollaw** [comment]
> ALT + SHIFT + TAB does (I hope predictably) inversion of ALT + TAB so cycles one window back

Not doing that, here. Should it do it?

Perhaps another shortcut? I had 15 spreadsheets open today and was trying to get back and forth between LibreOffice and my browser, it was pretty comical.

**Comment by olo2552** [comment]
Use one desktop for browser, and second desktop for spreadsheets then. Operating system isn't directli responsible for your workflow. I don't consider this issue fixable, nor high priority - but maybe I don't get the point.

**Comment by nkkollaw** [comment]
I don't think you do.

**Comment by cassidyjames** [comment]
Most apps in elementary OS are designed around having a single window, anyway, so in those cases Alt+Tab already effectively switches between apps. The problem with enforcing the app-based switching is that for those apps that do have more than one window, it becomes difficult to get to the other windows and it also messes up the window ordering of Alt+Tab (you can no longer tap Alt+Tab to switch to the window that was previously focused, because it might be a window of the same app).

After speaking with other designers in GNOME, it seems that the app-based switching in GNOME Shell is seen by some as problematic as well, for similar reasons.

I would be interested in a better design for alt+tab, but I don't think app-based is something we should do.
