### ISSUE TITLE
After the OS wakes from sleep multiple times, gestures start working improperly.

### ISSUE THREAD

**Issue by theuser18** [elementary/gala#1251]
## What Happened
When eOS has been running for awhile and awoken from sleep multiple times, gestures start to work improperly. A two finger tap no longer right clicks, instead, it will take you to the multitasking section. A single tap can also cause the same problem.

## Expected Behavior
Gestures should work as intended 100% of the time.

## Steps to Reproduce
Unfortunately, I am unable to specifically lay out a step by step process. The following is what I have generally observed but I do not know the causal steps. It has happened multiple times. A reboot solves the problem temporarily.

1. Boot into eOS.
2. Use the operating system.
3. Let the OS go to sleep and awake it multiple times.
4. Once awoken, gestures can stop working properly.

### Logs
I can provide one once I am able to reproduce the problem, but I do not know how to accurately reproduce it and I do not know how to take a log of it.

## Platform Information
Up to  date eOS 6.

Device 'SynPS/2 Synaptics TouchPad'

**Comment by JoseExposito** [comment]
Hi, thanks for reporting this issue.

This is most likely not a bug in Gala. Probably on libinput or Mutter.

The best way to debug the problem would be to have a look to your device logs. If you could attach the output of the following command when gestures work as expected *and* after reproducing the bug, it'd really help to fix it:

- `sudo libinput record`
- `sudo libinput debug-events --verbose`

In order to keep the logs short and easy to understand, while gestures are working:

- Run `sudo libinput record` and perform a 3 and 4 finger swipe
- Run `sudo libinput debug-events --verbose` and repeat

Try to reproduce the bug you mentioned and:

- Run `sudo libinput record` and perform one of those buggy 1 or 2 finger tap that open the multitasking view
- Run `sudo libinput debug-events --verbose` and repeat

**Comment by theuser18** [comment]
I am not sure how relevant it is to the issue but running `sudo libinput record` returns "sudo: libinput: command not found."

**Comment by JoseExposito** [comment]
You need to install it:

```bash
$ sudo apt install libinput-tools
```

**Comment by theuser18** [comment]
> You need to install it:
> 
> ```shell
> $ sudo apt install libinput-tools
> ```

I have not been able to reproduce it since filing the comment. It must have been fixed soon after.
