### ISSUE TITLE
Steam Users: What happens when you switch workspace while in a fullscreen game?

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#131]
Hi.  

1 - Open library window in workspace 1

2 - Start a game in fullscreen. Workspace 2 is created with the game in fullscreen.

3- If i choose another workspace, the game minimizes to workspace 1 and leaves an empty workspace 2.  

4- If i press alt+tab on workspace 1 the game creates a workspace 3 and goes to fullscreen.

I guess what should happen is that if i selected another workspace the game should remain in workspace 2 in fullscreen, but this is not happening on my computer.

Is this happening to other people?

**Comment by peteruithoven** [comment]
Do you have this with multiple games? Which games? 

At step 3, how do you choose another workspace? super+left for example? 

I'm not sure if this is relevant, but which graphics card are you using? You could check this by running:
```
$ glxinfo | grep OpenGL
```

I can't reproduce the issue consistently. 
**Team Fortress**
With Team Fortress I also notice that when I switch away from the game using Super+left it minimizes and at that point I have 3 workspaces. I need to press alt+tab to get back to the game, which then runs in workspace 3. I think this is the same issue as you are describing. 

**Factorio**
It starts in workspace 2 and I can simply switch between workspaces as one would expect.

**Comment by Astro-City** [comment]
Hi.  

Thanks for your reply.  

So far i tried two games and both show the same behaviour.  Volgarr and Deponia.  

Every method that i tried to choose another workspace makes it go first to the workspace that have the library window open and only then i can choose another workspace.
Imagine the following scenario:  

workspace 1 terminal
workspace 2 Steam Library

If i start a game in fullscreen mode, workspace 3 is created.

If i press super+1, the game minimizes and I'm back in workspace 2 with the game minimized in workspace 2 and an empty workspace 3. 

I i press alt+tab on workspace 2, the game goes fullscreen and workspace 4 is created.  

If i press super+left or super+number I'm always back on workspace 2 with the game minimized in workspace 2 and workspace 3 and 4 empty.  

In order to remove workspace 3 and 4, i have to select them by pressing super+right until I'm on the "+" workspace.  

I searched some solutions and this seems to be happening because when games loose focus they minimize.  

[https://askubuntu.com/questions/906328/games-minimize-on-steam](url) and [https://steamcommunity.com/app/221410/discussions/0/626329820878430425/](url) links seems to be about this issue.

Your Team Fortress seems similar to mine, but yours seems to return always to the same workspace and on mine it alway give me a new workspace even if there is an already empty workspace.  

Thanks and sorry for the big post.

**Comment by peteruithoven** [comment]
(Those links point to `https://github.com/elementary/gala/issues/url` )

**Comment by Astro-City** [comment]
Hi.  

Sorry about the links.  

The solution didn't work for me on both games.  

On Team Fortress does the game stays minimized on a different workspace where the library is or you see the same behavior that i described?

This is an unrelated question, but could you also tell me if when you watch a trailer in the steam app and put it in fullscreen, does it also stay on the bottom left of the screen instead of expanding to fullscreen?

**Comment by Astro-City** [comment]
Hi.  

I think that putting the following line on the .profile file in your home folder and restarting seems to solve the issue.

export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
