### ISSUE TITLE
Firefox does not pick up the system dark mode even when using its system theme

### ISSUE THREAD

**Issue by hirusi** [elementary/gala#1350]
### What Happened?

I noticed that Firefox's shell/window elements do not change with the OS, despite the relevant theme being selected for Firefox.

elementary OS:

![image](https://user-images.githubusercontent.com/3974019/147104927-30dfd6af-b605-4f59-a2df-e28f139a5dda.png)

Firefox 95:

![image](https://user-images.githubusercontent.com/3974019/147104814-dfa114dc-3763-450b-894c-ff5f4edc6b64.png)

### Steps to Reproduce

1. Install all updates
2. Install `firefox` from the apt repositories.
3. Configure Firefox to use system theme (default). Changes between light/dark modes.
4. Configure elementary OS to switch to/from dark mode automatically upon sunset/sunrise.
5. Firefox does not use its dark theme.

### Expected Behavior

Firefox, like it does in GNOME, should automatically change to dark theme when the OS is in dark mode/switches to dark mode.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

NVIDIA GTX 1050M.

**Comment by danrabbit** [comment]
I'm guessing this version of Firefox probably uses some GNOME specific setting. Firefox needs to be updated to support the FreeDesktop.org color scheme preference that was shipped in elementary earlier this year and will soon be shipped in GNOME and KDE

Closing as "out of scope" since this is a bug in Firefox and not in elementary OS

**Comment by hirusi** [comment]
Thanks Danielle.

For anyone else curious, follow the progress here - https://bugzilla.mozilla.org/show_bug.cgi?id=1734934.
