### ISSUE TITLE
Session crash when double right clicking on an app's window border (Fedora 36)

### ISSUE THREAD

**Issue by Cherryda** [elementary/gala#1420]
## What Happened?

When double right clicking any graphical app under Pantheon, the session will display a crash error instantly, forcing the user to log out.
Additionally, a single right click does not show the window's menu.

## Steps to reproduce

1- Install Fedora 36
2- Install the pantheon desktop from decatorphe's copr
3- Double right click a GUI app

## Expected Behavior

Right clicking should display the window's menu (such as, Stay on top, Always visible etc)
Double right clicking should not produce a session crash.

## OS Version

Fedora Linux Workstation 36

## Gala version

Gala 6.3.1 (gala-6.3.1-2.fc36.src.rpm)

**Comment by davidmhewitt** [comment]
This is probably already fixed in https://github.com/elementary/gala/pull/1411, but not yet released in a stable version of gala. It relates to newer versions of Mutter that we don't (yet) ship in elementary, so it doesn't affect us on elementary.

I'm not sure if that fix would be backported by Fedora packagers, or whether you'd only get that fix when we release the next stable version.

@decathorpe  ?

**Comment by decathorpe** [comment]
I already started including some commits from after 6.3.1, but apparently I missed some candidates. So if I know that the linked PR fixes a problem, I can add it to the Fedora gala package, sure.

**Comment by decathorpe** [comment]
Can confirm that applying the patch from the PR fixes this crash on Fedora 36. I'll submit an update in a few minutes.
