### ISSUE TITLE
[Bug] Hotkeys are not working with non-EN keyboard layout

### ISSUE THREAD

**Issue by Arakhis** [elementary/gala#1566]
### What Happened?

**Hotkeys are not working with non-EN keyboard layout**
That is not the first time I had this problem. Maybe on elementary 5 i seen this before.
Really awful thing. See steps to reproduce

**Also in games**, you need to change layout to use any keys. Dota 2 as example

### Steps to Reproduce

1. Install Elementary
2. Add Russian keyboard layout
3. Switch to Russian layout by Alt+Shift
4. Try to use hotkeys
5. Not working
6. Switch to English layout by Alt+Shift
7. Working

### Expected Behavior

I wanted to use hotkeys with any keyboard layout, as it works on other distros

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
> In elementary OS 7 it works fine only for US->RU. To switch from RU to US I need to press ALT+SHIFT twice. This is extremely inconvenient.

I tried adding the Russian keyboard layout and can confirm this issue too. Now I have the Russian and Japanese keyboard layouts, and switching from Japanese keyboard to Russian keyboard requires Alt + Shift once, but Russian to Japanese requires twice.

> @ryonakano you seem to be more familiar with input methods, do you know if there is a way to disable input methods like in OS 6?

We can kill it by running `$ killall ibus-daemon`, but I confirmed the issue persists after that.

**Comment by ryonakano** [comment]
Hmm, this is not relevant to Gala, but it's responsible to the keyboard plug, but even if I kill ibus-daemon it tries to switch to the IBus input methods (and failing because ibus-daemon is not running):

![Peek 2023-03-06 20-32](https://user-images.githubusercontent.com/26003928/223098844-ddfe1422-941f-40ea-9552-67006752065f.gif)

I did the following things in the video above:

- Kill ibus-daemon
- Open keyboard plug to see what happens if pressing Alt + Shift
- Press Alt + Shift, the keyboard layout switches from Japanese to Russian
- Press Alt + Shift again, the keyboard layout won't switch to Japanese and instead the following error message is shown:

```
(io.elementary.switchboard:5318): IBUS-CRITICAL **: 20:26:46.293: ibus_bus_call_sync: assertion 'ibus_bus_is_connected (bus)' failed
```

**Comment by ryonakano** [comment]
This should be a code in Gala which triggered when pressing `Alt + Shift`:

https://github.com/elementary/gala/blob/master/src/KeyboardManager.vala

**Comment by ryonakano** [comment]
> Reproduce 1:
> RU by default, EN secondary layout
> Starting PC
> RU is default on login screen, change layout
> Enter wrong password
> Layout resets to default RU, need to change again.

I installed elementary OS in Russian (select Russian as the system language and default keyboard layout) on a virtual machine and can reproduce this too:

[eOS Russian-screen0.webm](https://user-images.githubusercontent.com/26003928/223112763-4d332c33-e99c-47dc-b8ac-0636e0839e07.webm)
