### ISSUE TITLE
Alt+Tab menu could be considerably better

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/gala#1597]
### Problem

Elementary is the only Linux distro that feels like a true os to me. Like it's really consistent, more than Windows and Mac. But there's 1 thing that doesn't feel good: the alt+tab menu. It just feels bland and like any other KDE/GNOME interface element. It really feels out of place.

### Proposal

The solution needs to be debated, but I propose something like this:
![image](https://user-images.githubusercontent.com/46191980/228568338-9a1ac35d-1ae7-4b73-8715-593131a430ad.png)

**Comment by danirabbit** [comment]
Hey thanks for filing an issue report! There’s a fairly comprehensive discussion of alt tab behavior here: https://github.com/elementary/gala/discussions/72

it would be appreciated to consolidate the conversation in one place :) Closing as a duplicate since there’s already a place to discuss the alt tab design
