### ISSUE TITLE
Notifications appear in the center of the screen on Wayland

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1693]
### What Happened?

On Wayland, notification windows appear in the center of the screen instead of in the top right (or top left for RTL)

### Steps to Reproduce

1. Run a Wayland session
2. Receive a notification
3. See that the notification window is centered on the display instead of in the top corner

### Expected Behavior

Notifications should be aligned top right for LTR and top left for RTL

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by Marukesu** [comment]
(stealing this issue a bit for a more overall view to how integrate system components with gala in wayland, this text is also valid as solution to #1694 and elementary/switchboard-plug-display#352)

I though about this a little some time ago, i think we can use a "wayland protocol as DBus interfaces" concept, and then make it a proper wayland protocol when we have the tools to do it.

For now, we can go with something like this:
```
 // base interface that would be also implemented by the "derived" interfaces,
 // something like the "xdg_surface" providing a role property to be set by others 
 // interfaces.
 @interface io.elementary.Gala.Surface {
     @property role: (s) // possibly values would be "notification", "bubble", and "panel"
 }

 // for wingpanel and dock
 @interface io.elementry.Gala.Panel {
     @property anchor: (i) // top, bottom, left, right
 }

 // for the display labels that switchboard uses
 @interface io.elementary.Gala.Bubble {
     @property anchor: (i) // top, top_left, top_right, etc... 
 }
```

The way this would work is that applications would export the interfaces in the window's object path set with `gtk_shell.set_dbus_properties` method in wayland, or the `_GTK_WINDOW_OBJECT_PATH` xprop in x11. In gala, we would lookup the path to see if the interfaces exists and handle the Meta.Window as expected.

The major issue with this is that `Gdk.Wayland.Toplevel.set_dbus_properties()` is private in Gtk4. However, this would allow us to design and make use of what would look like, more or less, a wayland surface, making more easy to move from DBus interfaces to a wayland protocol in the future.

**Comment by davidmhewitt** [comment]
I haven't looked at it for a while, but Mutter has a concept of shell subprocesses built in (I can't remember what they call it now).

But if we used that, it would essentially make Gala responsible for starting the Dock and the panel and maybe the notification server. But, the fact that they're trusted subprocesses allows them to set some of the custom hints, like removing themselves from the dock and Alt+Tab switcher, and because Gala is tracking those processes, it could position their windows into the correct places.

I think this would solve a bunch of these kind of use cases, without having to implement a DBus API.
