### ISSUE TITLE
Window menus are not scaled correctly for HiDPI [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#175]
It looks like the font size is doubled, but the actual scale of the surface is half sized

---
There is a bounty on this issue [on Bountysource](https://www.bountysource.com/issues/55060509-window-menus-are-not-scaled-correctly-for-hidpi)

**Comment by davidmhewitt** [comment]
Was this the case on Loki too?

I've tracked down the cause of this (essentially because we're using a GTK Menu widget inside a non-GTK application, it doesn't receive the scaling factor from GDK properly).

I have a plan to resolve this, but it's a bit of work, I'll self assign for now and see where I get to.

**Comment by danrabbit** [comment]
Yes as far as I know this was also the case in Loki
