### ISSUE TITLE
Save vertical space

### ISSUE THREAD

**Issue by liminspace** [elementary/gala#181]
Hi!
Is it possible to make DE more ergonomic to save vertical space as Unity does?
Nowadays vertical space is more necessary than horizontal one. 
It's a very good idea to merge top panel of maximized window and wingpanel.

**Comment by peteruithoven** [comment]
I think that's a bit too general of a suggestion? 
See: https://elementary.io/get-involved#design

**Comment by liminspace** [comment]
Yes it's a general suggestion but it has sense because a lot of people like unity for its ergonomic. But unity died and a lot of people will be look for a worthy replacement. I think it's a very good reason to use this concept.

**Comment by danrabbit** [comment]
Since Gala is not responsible for drawing window decorations or the panel, this issue is out of scope for Gala.

Native apps for elementary OS use Gtk.Headerbar which already saves as much space in window decorations as is possible. If you see an application that is wasting space, please report an issue against that app, since it is responsible for drawing its own decorations.
