### ISSUE TITLE
API for display labels

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1823]
### Problem

In System Settings we have colored display labels that we set while the display configuration page is open. However we won't be able to position those windows in GTK 4/Wayland

### Proposal

Some kind of API either to position those windows as with the Dock and Panel

OR

Draw these labels in Gala and a simple API to show/hide them

### Prior Art (Optional)

https://github.com/elementary/switchboard-plug-display/blob/master/src/Widgets/DisplayWindow.vala

**Comment by Marukesu** [comment]
GNOME Shell has `org.gnome.Shell.ShowMonitorLabels` and `org.gnome.Shell.HideMonitorLabels` DBus methods. We can implement those on our version of the Shell interface.

I think the labels are simply enough to be written in clutter. otherwise we could move them to gala-daemon and use Meta.WaylandClient for positioning.
