### ISSUE TITLE
No app icons in Multitasking View, Window Switcher under Wayland

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1933]
### What Happened?

There are no app icons in the alt+tab window switcher or the multitasking view when running under wayland

### Steps to Reproduce

![Screenshot from 2024-05-29 08 21 39](https://github.com/elementary/gala/assets/7277719/989a0e31-f79a-4a17-b960-fdac8250d7fd)
![Screenshot from 2024-05-29 08 21 54](https://github.com/elementary/gala/assets/7277719/e98bf5aa-1d90-47df-974b-7c4262123145)

### Expected Behavior

App icons :)

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

**Comment by leolost2605** [comment]
Okay I thought this was only an issue because I installed on top of a regular Ubuntu 24.04 install but that seems to be not the case :sweat_smile: 
I'll try looking into it now
Maybe worth noting is that firefox for some reason has an icon (what's strange here is that it's installed as a snap because I didn't bother changing it)
