### ISSUE TITLE
Don't fullscreen to new workspace with multi-monitors

### ISSUE THREAD

**Issue by codygarver** [elementary/gala#230]
I drag a window over to my second display and fullscreen it, then it clears everything on the primary display, which isn't helpful.

**Comment by Philip-Scott** [comment]
Hmmmm i'm not able to reproduce it. Currently on Juno with all updates applied. These are the steps i followed: 

- Open 3 windows on the primary display (Videos being one of them)
- Drag window to secondary monitor
- Fullscreen

Video gets full-screened, but the main display does not move to another desktop. Can you share your display setup and steps to reproduce it?

**Comment by emilioestebanez** [comment]
I have this issue on Juno with all updates up to July 20th.

I go to youtube.com in my main monitor and open any video. I click on full-screen and it shows an animation as when switching workspaces and the video plays full screen without issues.

If I do the same in a secondary window, it tries to do the same "change workspace" animation, but it glitches (since there are no workspaces in the secondary monitor) and either never switches to full screen or when it does, the video stutters.

If I open it on the main monitor, click on full screen and then I move it to the secondary monitor with Super+Shift+RightArrow then it keeps playing the video without stuttering.

**Comment by jlnr** [comment]
I'm using the current Juno daily build with two screens and cannot reproduce this. If this bug affects you, how are your screens arranged, and which browser did you use for the YouTube fullscreen test?

**Comment by emilioestebanez** [comment]
Hi @jlnr ,

You can reproduce it in a clean installation of Juno beta2 in VirtualBox. I leave here a Virtualbox image that you can try:
https://drive.google.com/open?id=1i_uo5qlynas3euiuMaBxemfZK_WPdY8S

1. Just enable the second monitor in VirtualBox
2. Open Elementary's browser, maximize it and move it to monitor 1
3. Open any Youtube video and make the video full screen. At this point it all should be OK
4. Exit the full screen video
5. Now move the browser's window to the second monitor and maximize the browser
6. Open again any Youtube video and make the video full screen. At this point the animation would get stuck and/or not reach full screen. You can press ESC to exit this state and try again.

I've found that if the browser is not maximized it sometimes works, but with the browser window maximized it gets stuck if you follow exactly those steps.

Best regards,
Emilio

**Comment by gavr123456789** [comment]
I have same problem

**Comment by lenemter** [comment]
Closing the issue as stale. If you still encounter it please reply here.
