### ISSUE TITLE
Elementary Design Needs a new typeface

### ISSUE THREAD

**Issue by aggalex** [elementary/gala#234]
Roboto looks old and too simple. I'd suggest Now Open Source TypeFace, a nice geometric typeface. http://www.1001fonts.com/now-font.html

**Comment by cassidyjames** [comment]
1. This is the repository for the window manager and has nothing to do with fonts or typefaces.

2. elementary OS does not use Roboto. We use Open Sans for the majority of the UI and Raleway for some headings and accents. We use Roboto Mono for the monospace font, because it is high quality and somewhat similar in style to Open Sans.

3. For a UI typeface, we intend for it to be simple and unassuming. For headings, we use Raleway which has a bit of a geometric look and is what our logotype is based on. We're not looking to rebrand at this time (which we would need to do if we changed Raleway).
