### ISSUE TITLE
Telegram tray icons does not shown in Juno

### ISSUE THREAD

**Issue by LvLs9** [elementary/gala#284]
![image](https://user-images.githubusercontent.com/34302242/42295993-ea09c340-7ff8-11e8-9b4d-dba39b20e0f6.png)

**Comment by danrabbit** [comment]
Gala doesn't have any influence over the panel, so this issue report is out of scope for Gala.

If Telegram uses the Ayatana indicator API, you probably have to install `wingpanel-indicator-ayatana`. Otherwise, if they're using the old gnome status icons API this just doesn't work with Juno and they need to update.

Closing as "Out of scope" since nothing can be done in Gala to fix this
