### ISSUE TITLE
Gala doesn't respect "cursor-size" settings

### ISSUE THREAD

**Issue by alex285** [elementary/gala#300]
elementary: 5.0
Gala: 0.3.1

### Reproduce
Open dconf-editor to `org.gnome.desktop.interface` and set `cursor-size 48`

![cursor-size](https://user-images.githubusercontent.com/11244308/42891110-3e9fa7ee-8ab7-11e8-94ba-aade9997327c.png)

### Output
The cursor now behaves on 48px on overview mode (eg Multitasking View) or on windows hover, but it gets back 24px on CSD headerbars, and background / desktop hover

### Further investigation
If we install `gdm3` and login with GDM, Gala will respect cursor-size in all cases. I can reproduce the same issue on my Fedora 28/29 when I login with LightDM

**Comment by kyentei** [comment]
When logging in with lightdm, using the pantheon greeter, the scaling seems broken except inside gtk2 applications (such as firefox). Logging in using the lightdm-gtk-greeter seems to fix it, just like using gdm fixes it.

I think the problem is caused by the lightdm pantheon greeter.

Tested on an XPS 13 (9360) using both Fedora and Elementary OS.

**Comment by kyentei** [comment]
using `lightdm-gtk-greeter` fixes the cursor scaling issue.

**Comment by kyentei** [comment]
Possibly related to https://github.com/elementary/greeter/issues/149
