### ISSUE TITLE
SSD windows have very strong shadows

### ISSUE THREAD

**Issue by wout** [elementary/gala#391]
A minor issue, but it's not really pleasant on the eyes. This is the drop shadow of System Settings, which is fine:

![eos-system-settings](https://user-images.githubusercontent.com/107324/47576296-69278000-d944-11e8-936a-0fcf8c08b932.png)

But with Slack:

![eos-snap-slack](https://user-images.githubusercontent.com/107324/47576345-7d6b7d00-d944-11e8-98ff-ce9a5732792a.png)

Or with Gravit Designer:

![eos-snap-gravit](https://user-images.githubusercontent.com/107324/47576351-80ff0400-d944-11e8-8b47-69b325af8609.png)

Shadows are really intense, too intense for my taste.

**Comment by Exalm** [comment]
![Screenshot from 2019-10-23 08-52-39](https://user-images.githubusercontent.com/1510457/67356098-9f441380-f548-11e9-9e3b-f1fda7c2c83b.png)

It's not because of Snap, but because those apps are using legacy decorations.

Here gala (well, mutter) assumes that GTK stylesheet only specifies a border in `.ssd decoration` style. See this line in Adwaita: https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/theme/Adwaita/_common.scss#L4497

elementary stylesheet doesn't do this, so mutter draws the default shadow + full box-shadow from stylesheet, so there are 2 shadows on top of each other.

**Comment by Exalm** [comment]
The stylesheet fix has landed, now it needs to be fixed in Gala.

While shadow gsettings keys indeed need to be [removed](https://github.com/elementary/gala/issues/511), they are handy for playing with the shadows right now.

**Comment by danrabbit** [comment]
@Exalm that's a massive improvement. Nice work! Happy to merge that
