### ISSUE TITLE
Brightness adjustment

### ISSUE THREAD

**Issue by macgarcia** [elementary/gala#550]
Brightness adjustment, through F11 and F12, interface stops.

**Comment by FernandoLGL** [comment]
Hi, it only happens with brightness. It could be the brightness notification, yes. Other notifications are fine, however.

Answering your questions:
1. "Does it happen on a clean system?"
A: Not at the same degree, but it still shows clear signs that it's not as smooth as the sound notification, for example, cause it looks really slow and doesn't update in real time(it has a delay of like a quarter of a second). It actually doesn't "crash" your system (by "crash" I really do mean freeze, like you said).

2. "Does it only happen when you alter brightness or also with other keyboard shortcuts?"
A: Only brightness, the other shortcuts are fine

3. "Does it also happen when you alter the brightness through the power indicator or settings?"
A: No it does not, and that's the way I've been altering the brightness since Juno. But when I restarted after recording a video demonstrating what happens, the brightness controls were not responding anymore. When I restarted the second time it did work as it normally does.

I have recorded several videos that should show you exactly what's happening, but I don't know how to share them with you securely
