### ISSUE TITLE
Use wayland for Window manager 

### ISSUE THREAD

**Issue by mathpfvr** [elementary/gala#586]
Please use wayland as window manager, it would make the system lighter compared to GTK

**Comment by jlnr** [comment]
This topic comes up on reddit every now and then, [here's one recent response](https://www.reddit.com/r/linux/comments/9h5h1w/we_are_elementary_ama/e699zlg/). It's definitely on the roadmap, but note that moving from X to Wayland will not change the fact that apps are built using GTK.

I will close this issue as a duplicate because more concrete work items like #68 and #70 already exist.
