### ISSUE TITLE
Drop down windows artifacts with mutter possibly 

### ISSUE THREAD

**Issue by slclements78** [elementary/gala#615]
There are artifacts from drop down menus etc in different programs like Firefox, Inkscape, Kdenlive and several others. I read where it's related to Mutter but can't find out how to resolve it from the sources i found. When i try to take a screen shot it goes away.

**Comment by Blast-City** [comment]
Hi.
This is a known issue and have been reported on #605.
You should close this issue since it's a duplicate.

**Comment by slclements78** [comment]
When is there going to be a fix or is there already????

**Comment by Blast-City** [comment]
Hi.
I don't know. Sorry.

**Comment by ryonakano** [comment]
Thank you for your reporting. I'll close this as a duplicate of #605.

This issue seems to be [an upstream (mutter) issue](https://gitlab.gnome.org/GNOME/mutter/issues/536) and [some downstream like NixOS uses a patch to fix this issue](https://github.com/elementary/gala/issues/605#issuecomment-531613377).

**Comment by slclements78** [comment]
Thanks
