### ISSUE TITLE
Cannot permission FTP

### ISSUE THREAD

**Issue by sugandaaa** [elementary/gala#67]
Hi, why can't remove file in my hosting. I am login using my root account. 
But why like this?
![screenshot from 2017-09-01 22-07-13](https://user-images.githubusercontent.com/15070585/29975865-398577e4-8f62-11e7-93e7-288097042146.png)

**Comment by btkostner** [comment]
I'm going to guess that you have weird permissions for that file, but I could be wrong. Either way, you will have better luck asking in [stackexchange](https://elementaryos.stackexchange.com/questions/tagged/pantheon-files) because this repository is for the elementary window manager. 

Closing as invalid.
