### ISSUE TITLE
Wayland: design window communication API

### ISSUE THREAD

**Issue by donadigo** [elementary/gala#68]
We should design a way to inspect and interact with windows that are currently running, possibly through DBus.

Couple of features that I think should be implemented within the server:
1. Get a list of currently opened windows
2. Get information about a particular window:
 * Title
 * State (minimized, maximized)
 * Type (normal, desktop, dock etc.)
 * Icon
 * Size and position
 * The workspace it's currently on
 * The screen it's currently on
 * Process ID
 * Where in the window stack the window is (on top, on bottom)
 * Possibly a unique ID (not needed with DBus)

3. Performing different actions on a particular window:
 * Minimizing
 * Unminizing
 * Unmaximizing
 * Maximizing
 * Activating
 * Closing
 * Moving to a particular workspace
 * Changing it's size and position (for dock windows)

4. Receiving information about events:
 * Window workspace changed
 * Window closed
 * Window state changed (minimized, maximized etc.)
 * Window name changed

Feel free to discuss the API in the comments.

**Comment by matzipan** [comment]
Who can access this dbus? Any process about any window?

**Comment by donadigo** [comment]
I think any application can now access this information through libbamf and libwnck, so there is no difference although, since we will be implementing this API, we can restrict the access to this information.

**Comment by matzipan** [comment]
> I think any application can now access this information through libbamf and libwnck

Sure, but this is a problem and we shouldn't propagate this to wayland-land.

**Comment by trickreich** [comment]
Any process on this?

**Comment by properlypurple** [comment]
This should be a good starting point
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/xdg-shell/xdg-shell.xml

**Comment by Congee** [comment]
It's been ... one year since the last reply 😕

**Comment by orowith2os** [comment]
What are the topics that need to be discussed here now? The Wayland protocol (wayland and wayland-protocols) should handle everything for clients, and for the shell, you can look into how KDE/kwin and Sway/wlroots handle it. 

Being based on Mutter, it might be preferable to investigate how GNOME Shell manages everything.

**Comment by lenemter** [comment]
@orowith2os Currently discussions are taking place in https://github.com/elementary/gala/issues/1693.

> and for the shell

I think Mutter doesn't allow that by default. See https://gitlab.gnome.org/GNOME/mutter/-/issues/1922 and https://gitlab.gnome.org/GNOME/mutter/-/issues/1053.

> you can look into how KDE/kwin and Sway/wlroots handle it

We use Mutter, which is made for gnome-shell, and they aren't going to implement anything from KDE/kwin or Sway/wlroots because "that is not how GNOME is designed to work" (see https://gitlab.gnome.org/GNOME/mutter/-/issues/973)

> Being based on Mutter, it might be preferable to investigate how GNOME Shell manages everything.

AFAIK GNOME Shell is monolithic. Every single part of it (panel, notifications, dock) is built into GNOME Shell, while we use separate panel, notification server and dock. So we can't just copy-paste code from gnome shell.
