### ISSUE TITLE
Zoom with Super + Scroll

### ISSUE THREAD

**Issue by techdev5521** [elementary/gala#815]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

I'm visually impaired and would like to invoke the screen magnifier with <kbd>Ctrl</kbd> + Scroll like macOS so that I don't have to take my hand off my mouse to zoom in and zoom out as I change zoom levels several times a minute and this slows me down.

**Describe the solution you'd like**

macOS allows the magnifier to be invoked with <kbd>Ctrl</kbd> + Scroll. I'd like similar functionality.

**Existing work**

On Gnome Shell proper, this functionality was achieved with this project: https://github.com/tobiasquinn/gnome-shell-mousewheel-zoom 

**Describe alternatives you've considered**

- Continue using the keyboard shortcut

**Additional context**

I've been looking into tobiasquinn's project to understand how it works (for about 20 minutes) and am willing to contribute code when I understand both that project and Gala enough to do so. Any help is appreciated.

**Comment by cassidyjames** [comment]
I think we'd do Super + Scroll since Super is window-manager-level stuff, and many apps have Ctrl + Scroll for zooming inside the app. But otherwise I'm :+1:

**Comment by janxkoci** [comment]
This could also help avoid some locale-specific collisions: When my zoom works properly with the shortcut `Super`+`+`, then I can no longer use `Super`+`1` to switch to 1st workspace, because in Czech locale the symbols `1` and `+` are on the same key (the key above a letter `Q`). I currently experience a race condition after reboots when some sessions have that key set as `+` (so pressing the combo starts zooming) and other sessions have it set as `1` (so pressing the combo switches to 1st workspace).

**Comment by cassidyjames** [comment]
For touchpads we do already support multi-touch zooming as well, through System Settings → Mouse & Touchpad → Gestures.
