### ISSUE TITLE
PIP windows are present when session is locked

### ISSUE THREAD

**Issue by megatux** [elementary/gala#837]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When the session is locked the Picture In Picture windows should not be visible at all. I consider this issue is a privacy concern.

### To Reproduce
1. create a PiP
2. lock the session or wait until the autolock (or wallpaper-only view, not sure what it is called) is triggered.
4. See privacy leak

### Expected behavior
No data from user session should be displayed on a _locked_ session.

## Platform Information
 - OS: elementary OS, 5.1.5 Hera

**Comment by davidmhewitt** [comment]
What does your screen look like when it's locked?

It should switch back to the greeter/login dialog. I don't understand what you mean by "wallpaper-only view".

**Comment by megatux** [comment]
Oooh, more info:  the PIP that are displayed are the ones on the second monitor, not the main one with the password input. Attaching photo made with mobile:

![Captura de pantalla de 2020-06-04 11-19-28](https://user-images.githubusercontent.com/850020/83768543-4ea3a580-a655-11ea-9b51-d35b54c4ea86.png)

With "wallpaper-only view" I mean when I wait 1 or 2 mins, the screen windows are gone and only the wallpaper is displayed. If I move mouse or touch keyboard then the complete state of windows is restored. Not sure how to call this "feature".

Attaching energy settings screen, just in case:
![Captura de pantalla de 2020-06-04 11-16-36](https://user-images.githubusercontent.com/850020/83768278-f371b300-a654-11ea-8655-f70757b65703.png)

**Comment by davidmhewitt** [comment]
Something about your installation has been customized, the lock screen should exactly the same as the login screen which look like this:
https://raw.githubusercontent.com/elementary/greeter/master/data/screenshot.png

That lock screen does not look like a standard component of elementary.

**Comment by megatux** [comment]
I see. Sorry about my mixed DEs setup. Is this something Gala can fix on its side? the PIPs in the main screens are not displayed, only on the others.

**Comment by davidmhewitt** [comment]
The screen locking functionality will be done differently in elementary OS 6.0 with Gala handling it internally rather than relying on `light-locker` or whatever screensaver/screen locker you're using here. I'd have to check that this is handled properly with the new screen locker, but it should be.

This is not likely to be fixed in elementary OS 5.1 due to the fact it's only an issue with your specific configuration and we need to focus on working on the new verison. This doesn't happen if you use the stock elementary screen locking functionality. 

I'll close this issue as this is not a configuration we currently support but please re-open it or report another issue if this continues to be a problem in elementary OS 6.0 after it's released.

**Comment by megatux** [comment]
Sure, thanks! Do you know the Display Manager/Locker package names for eOS? I want to do a `dpkg-reconfigure light-locker` or similar, to restore the stock one.
