### ISSUE TITLE
Latest gala git doesn't start

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#853]
After installing any of the latest versions of Gala from git, gala can't initialise and gets stuck in a login loop. 
I have tried this on both Nvidia proprietary drivers, Nouveau and now the currently available Mesa drivers for the AMD RX470 (8 gig variant). I'm not sure whether or not I am missing something, as it seems to have the same issue on both my GPUs.

**Comment by davidmhewitt** [comment]
I'm going to assume you're trying this on elementary 5.1. If so, then there have been some things relating to notifications merged into gala that will cause issues when you install from git without first making sure there are no plugins left behind that try to use the old ABI.

I would guess that the old notification plugin is still installed from the stable version of gala and it is that which is causing the issues.

However, since the latest version of gala is no longer officially supporting elementary OS 5.1, I'll close this issue.
