### ISSUE TITLE
Minecraft launcher looks broken

### ISSUE THREAD

**Issue by kassindornelles** [elementary/gala#858]
Minecraft launcher looks broken on elementary os 5.1.5

![Captura de tela de 2020-06-23 20 10 56](https://user-images.githubusercontent.com/40970965/85476064-bfbbe600-b58d-11ea-9c99-131c607e3528.png)
![Captura de tela de 2020-06-23 20-01-37](https://user-images.githubusercontent.com/40970965/85476066-c21e4000-b58d-11ea-8b37-346a9cb42a75.png)

NVIDIA DRIVER: 440.59

**Video of the issue:**
https://streamable.com/g8t4y1

**Comment by kmandarin-orange** [comment]
I can confirm that this problem still happens with the Flatpak version as well, and it happens on a laptop without Nvidia graphics (Intel i3 8th gen CPU with integrated graphics). Looks like the problem has something to do with how the app draws shadows, because it seems to just pick up whatever is beneath the shadows when the window is moved.

**Comment by hanaral** [comment]
It is most likely to do with how the app draws it's own shadow, since it does not seem to comply the freedesktop standards for window composition (e.g. the launcher also doesn't actually maximise properly using the maximised state gsetting, and therefore does not retain that state after closing it).

**Comment by kassindornelles** [comment]
not sure if this got fixed in the latest eOS, but since i dont use it anymore and seems like this bug was ignored i am closing it.
