### ISSUE TITLE
CSD Firefox has no window border in 6.0

### ISSUE THREAD

**Issue by Zonnev** [elementary/gala#934]
In elementary OS 6.0 I see no window border on Firefox (81.0.2) with title bar disabled. With title bar enabled I see a border on the title bar, rest of the window has no border. 

With title bar enabled I also see a black square behind the window, which is not visible on screenshots. The black square is behind all popup windows from Firefox with a title bar on it.

![Schermafdruk van 2020-10-17 03 58 39](https://user-images.githubusercontent.com/32688765/96327545-ca1d5680-103a-11eb-990d-27b02194e201.png)
No window border with title bar disabled.

![Schermafdruk van 2020-10-17 03 59 20](https://user-images.githubusercontent.com/32688765/96327582-26807600-103b-11eb-8c5e-869e126e9ab8.png)
Window border only on title bar.

![Screenshot-from-2020-10-09-21-08-05](https://user-images.githubusercontent.com/32688765/96327709-1b7a1580-103c-11eb-8f3f-a95f9d836215.png)
Black square behind windows with title bar on.

**Comment by cassidyjames** [comment]
The black square thing is weird and might be due to some configuration in elementary OS not playing well with legacy windows; I have seen similar things when changing the scaling factor. The border issue looks like that's just a Firefox issue, as it is not using native GTK widgets there, and Gala has nothing to do with that; it is all client-side.
