### ISSUE TITLE
Which app am I in?

### ISSUE THREAD

**Issue by aral** [elementary/gala#982]
## Problem

![Screenshot from 2020-12-06 14-18-01@2x](https://user-images.githubusercontent.com/41798/101282641-2fd1c780-37ce-11eb-9c82-80fc15b8439b.png)

From the above screenshot, can someone please tell me which app I’m currently running and let me know how you managed to figure it out.

## Proposal

Display the name of the currently-running app.

One place where it would make sense is the status display at the middle of the of the top bar. It shows the current date and time, it would make sense to show the current app there too. e.g., 

```
🔍️ Applications                      Epiphany    Sun, Dec 6    14:24                     [icons]
```

## Prior Art

Knowing which app you’re currently in is a commonly implemented example of a basic landmark.

(Apologies for the huge screenshot, I’m posting this from elementary OS and I couldn’t find a crop tool in the Photos app.)

**Comment by cassidyjames** [comment]
It looks like Epiphany is focused here because it has the active window styling, which is higher contrast. The elementary stylesheet has a clear distinction between focused and unfocused windows—even moreso in the redesign coming for elementary OS 6; I think part of the problem here is that Firefox is not a native app and thus does not fully use the native stylesheet, and thus misses out on the nuances of that affordance. If Firefox used the native toolkit, it would be much more clear. This is a huge reason we are in favor of native apps that care about the platform on which they run, because we can insure these sort of affordances at the platform level.

Regarding your suggestion of showing the app name in the panel, I'm unsure that's a real solution for most situations. Multi-window apps are common, and showing the app name does not specify which window is focused. Trying to show more context (like a focused web page’s title or a focused document name) could work, but then that string quickly gets very long and dominates the entire panel, or must be truncated and lose context anyway.

Our chosen solution to this issue is to lean on the stylesheet. If it can be made more clear in the stylesheet, that's a stylesheet issue. If an app chooses not to use the platform stylesheet, there is only so much we can do while still optimizing for apps that _do_ care about the platform.

**Comment by aral** [comment]
But how do you know it’s Epiphany? And not Firefox?

**Comment by aral** [comment]
(My point isn’t which app is focused. I’ve never seen either app before. How do I know which is Epiphany and which is Firefox?

**Comment by danrabbit** [comment]
Okay, counterpoint: which app is this? :p

![image](https://user-images.githubusercontent.com/7277719/101296062-3c5a1e00-37d6-11eb-8d75-2f950b123756.png)

Presumably, you installed and opened these apps so I would assume you have knowledge of what you have done. But either way, does it really matter if you can see the content and interact with it and do the thing you set out to do?

**Comment by aral** [comment]
This is the equivalent screenshot from iOS:

![5F906CFF-8A27-41D6-92B9-52016605934F](https://user-images.githubusercontent.com/41798/101296468-be206a80-381b-11eb-868b-e427a0542e9e.png)

In a multi-window environment, not knowing which app is currently active is a basic usability flaw. You’re missing the most important landmark: where am I now?

**Comment by cassidyjames** [comment]
Just following up as this has seemed to be a multi-faceted issue; and to clarify, closing it doesn't mean we're not addressing those concerns. 

I've proposed https://github.com/elementary/stylesheet/pull/899 to further improve "backdrop" (unfocused window) distinction. We do show app icons in the multitasking view, and have plans to further improve the Alt+Tab window switching view to show window titles (https://github.com/elementary/gala/discussions/72).

It might make sense to convert this into a discussion since it's not a specific issue, but touches on several things.
