### ISSUE TITLE
Multitouch gestures have no upper speed limit

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#989]
## Problem

When performing multi-touch swipes, if you swipe fast enough there is no perceivable animation or transition. This ends up feeling kind of janky and not smooth

## Proposal

There should be some upper speed limit on transitions so that we're always at least getting some kind of animation. Maybe like a 200-300ms minimum animation time or something

## Prior Art

We should look at what Handy does here so that it feels internally consistent between app gestures and WM gestures

**Comment by danrabbit** [comment]
@Exalm if you could point to code in Handy or otherwise comment/explain what is done there that would be great :)

**Comment by Exalm** [comment]
libhandy clamps to [100:400] ms range.

**Comment by Exalm** [comment]
What you really want here is a spring animation and not to use velocity, but that's patented. 😒️

**Comment by JoseExposito** [comment]
@Exalm could you point me to the implementation of this in libhandy, please? I'll need to read a lot of libhandy's code to make this feel consistent.
Ideally, I'll like to also make the final transition kinetic and that should also be consistent with libhandy.

Just thinking out loud, as this could take a ridiculous amount of work or just not being possible, but since you are here, I can not loose the opportunity to ask you :smile:
I'm not familiar with libhandy's code, but... Do you think that it'll be possible to isolate the code in charge of calculating stuff like minimal animation duration, kinetic physics, etc and move it to a shared place?
I'll be happy do help with that upstream, and I think it could be very useful to many many projects out there, not just Gala.

**Comment by Exalm** [comment]
https://gitlab.gnome.org/GNOME/libhandy/blob/master/src/hdy-swipe-tracker.c#L325 it's literlaly just clamping. :p

**Comment by Exalm** [comment]
> Do you think that it'll be possible to isolate the code in charge of calculating stuff like minimal animation duration, kinetic physics, etc and move it to a shared place?

There aren't much physics there atm really. There is a big rework in https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/543 though, that one is actually physics-based.

I think sharing would be overkill here tbh, there's not _that_ much code, and e.g. WebKit won't want to depend on that so you'd still have copypasta.

**Comment by JoseExposito** [comment]
> https://gitlab.gnome.org/GNOME/libhandy/blob/master/src/hdy-swipe-tracker.c#L325 it's literlaly just clamping. :p

Thanks for the link!!
However, I don't think that clamping on `end` will fix what Daniel described. I'll need to do some work on `update` to limit how fast you can scroll or use non accelerated deltas from `libinput`.

> I think sharing would be overkill here tbh, there's not that much code

Fair enough. libhandy scroll tracker is really well written, so I won't have problems reusing some bits :D

Thanks Alexander!

**Comment by Exalm** [comment]
Ah, if it's about the swiping phase, then yes, you need unaccelerated deltas, OR otherwise you need a multiplier to unify it with scrolling: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/swipeTracker.js#L17

**Comment by JoseExposito** [comment]
OK, so I'm using unaccelerated deltas on the daemon side :+1: 

Also, as I normalize deltas before sending them to Gala, I'm differentiating between touchpad horizontal/vertical size for normalization.
Previously the smaller dimension of the touchpad (most likely the Y axis) was used for normalization. That's why this issue was more noticeable switching workspaces than showing the multitasking view.

Now, switching between workspaces really fast feels similar to switching between pages in the application launcher.
Just compile the latest master of Touchégg and let me know what do you think.

-------

One thing I noticed, and that we could explore in the future, is that on macOS it is not possible to fully swipe from one workspace to the next one in 1 swipe. I mean, if you start swiping from the left side of your touchpad, when your last finger reaches the right side of the toucpad the animation is not fully completed, there is a ~20% of the animation pending.
Because macOS has proper physics on this gestures, completing that ~20% feels really natural and smooth even with very fast swipes.
