### ISSUE TITLE
Touchégg workspace gestures stop working in Multitasking View

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#993]
## What Happened

I three-finger swipe up to go into the Multitasking View, then try to three-finger swipe left or right to switch workspaces.

## Expected Behavior

I expected three-finger swipes left/right to work in the Multitasking View.

## Steps to Reproduce

1. Enter the Multitasking View (via three-finger swipe, keyboard shortcut, or .desktop file)
2. Three-finger swipe left or right to a new workspace

## Platform Information

elementary OS 6 daily build, updated as of today.

**Comment by florisre** [comment]
Maybe a easy solution to this might be changing the behavior of three finger swiping up to the same as super+A, meaning that it shows all open windows and no workspaces?

**Comment by JoseExposito** [comment]
Yes, at the moment it is disabled on purpose:

```
            if (!wm.workspace_view.is_opened ()) {
                wm.switch_to_next_workspace (Meta.MotionDirection.RIGHT, hints);
            }
```

Because that animation is not 1:1, even when using 2 fingers swipes. If you remove that `if`, you'll notice that swiping bellow the gesture completion threshold will switch you back to the previous workspace.

The fix here is to make that animation 1:1, ideally both with 2 and 3/4 fingers.

**Comment by JoseExposito** [comment]
PR 1 of 2 ready for review https://github.com/elementary/gala/pull/1051

This one adds support for smooth scrolling, like in libinhandy.

**Comment by JoseExposito** [comment]
PR 2 of 2 is ready https://github.com/elementary/gala/pull/1063
